### ISSUE TITLE
Can't load native library

### ISSUE THREAD

**Issue by coachwei** [openvenues/jpostal#15]
When running test java code, got the following error (I added a "main" method to the TestAddressParser class):

```
$  java -classpath .:../../libs/jpostal.jar com.mapzen.jpostal.TestAddressParser 
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jpostal_parser in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.mapzen.jpostal.AddressParser.<clinit>(AddressParser.java:8)
	at com.mapzen.jpostal.TestAddressParser.testParse(TestAddressParser.java:17)
	at com.mapzen.jpostal.TestAddressParser.testParseUSAddress(TestAddressParser.java:54)
	at com.mapzen.jpostal.TestAddressParser.main(TestAddressParser.java:13)
```
Looks like that I need to set up the java.library.path (I checked this property. None of the directories that it points to have the libpostal library). What should I set to the java.library.path variable?

( I did built/installed libpostal and jpostal following the instructions on https://github.com/openvenues/jpostal)

**Comment by thatdatabaseguy** [comment]
From #3:

jpostal builds shared object files (.so on Linux, .jniLib on Mac) that also need to be on java.library.path (after you run gradle assemble the .so files can be found in build/natives in your checkout dir). For running the tests, we set this explicitly [here](https://github.com/openvenues/jpostal/blob/master/build.gradle#L18).

If you use gradle, there's a plugin called gradle-natives that may be helpful: https://github.com/cjstehno/coffeaelectronica/wiki/Going-Native-with-Gradle

**Comment by coachwei** [comment]
Thanks for the reply. 

It turns out setting java system property inside Java code may not work for java.library.path variable as it is really a "read-only" variable. 

Here is a link for reference purpose:
`http://stackoverflow.com/questions/5419039/is-djava-library-path-equivalent-to-system-setpropertyjava-library-path/24988095#24988095`

**Comment by thatdatabaseguy** [comment]
Right, that's why we set it in the gradle build, not in Java.
